version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm-alpine
    container_name: bb-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/app
    networks:
      - boxbilling-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: bb-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8004:80"
      - "447:443"
    volumes:
      - ./app:/var/www/html/app
      - ./docker-files/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - boxbilling-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: bb-db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: boxbilling_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - boxbilling-network

#Docker Networks
networks:
  boxbilling-network:
    driver: bridge